#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

mkdir -p config/sites/main
ln -snf ../../../.ddev/TYPO3/config.yaml config/sites/main/config.yaml
mkdir -p config/system
ln -snf ../../.ddev/TYPO3/settings.php config/system/settings.php

echo "Run 'composer install'"
ddev composer install

echo "Restarting DDEV to apply configuration"
ddev restart

echo "Executing TYPO3 Setup"
ddev exec ./.build/bin/typo3 setup
